

{{ simple_cte([
    ('structured_behavior', 'fct_behavior_structured_event'),
    ('event', 'dim_behavior_event'),
    ('namespace', 'dim_namespace'),
    ('project', 'dim_project'),
    ('operating_system', 'dim_behavior_operating_system'),
    ('dates', 'dim_date')
]) }}


SELECT
  structured_behavior.behavior_structured_event_pk,
  --structured_behavior.dim_behavior_website_page_sk,
  --structured_behavior.dim_behavior_referrer_page_sk,
  --structured_behavior.dim_behavior_browser_sk,
  --structured_behavior.dim_behavior_operating_system_sk,
  --structured_behavior.dim_namespace_id,
  --structured_behavior.dim_project_id,
  --structured_behavior.dim_behavior_event_sk,
  --structured_behavior.dvce_created_tstamp,
  structured_behavior.behavior_at,
  dates.date_actual AS behavior_date,
  --structured_behavior.tracker_version,
  --structured_behavior.session_index,
  structured_behavior.app_id,
  --structured_behavior.session_id,
  structured_behavior.user_snowplow_domain_id,
  --structured_behavior.contexts,
  --structured_behavior.page_url_host_path,
  --structured_behavior.page_url_path,
  --structured_behavior.page_url_scheme,
  --structured_behavior.page_url_host,
  --structured_behavior.page_url_fragment,
  --structured_behavior.gsc_google_analytics_client_id,
  structured_behavior.gsc_pseudonymized_user_id,
  --structured_behavior.gsc_environment,
  --structured_behavior.gsc_extra,
  structured_behavior.gsc_plan,
  structured_behavior.gsc_source,
  --structured_behavior.created_by,
  --structured_behavior.updated_by,
  --structured_behavior.model_created_date,
  --structured_behavior.model_updated_date,
  --structured_behavior.dbt_updated_at,
  --structured_behavior.dbt_created_at,
  structured_behavior.event_value,
  --event.dim_behavior_event_sk,
  --event.event,
  --event.event_name,
  --event.platform,
  --event.environment,
  event.event_category,
  event.event_action,
  --event.event_label,
  event.event_property,
  --event.max_timestamp,
  --event.created_by,
  --event.updated_by,
  --event.model_created_date,
  --event.model_updated_date,
  --event.dbt_updated_at,
  --namespace.dbt_created_at,
  namespace.dim_namespace_id,
  --namespace.namespace_is_internal,
  namespace.namespace_is_ultimate_parent,
  --namespace.namespace_name,
  --namespace.namespace_path,
  --namespace.owner_id,
  --namespace.namespace_type,
  --namespace.has_avatar,
  --namespace.created_at,
  --namespace.updated_at,
  --namespace.is_membership_locked,
  --namespace.has_request_access_enabled,
  --namespace.has_share_with_group_locked,
  --namespace.is_setup_for_company,
  --namespace.visibility_level,
  --namespace.ldap_sync_status,
  --namespace.ldap_sync_error,
  --namespace.ldap_sync_last_update_at,
  --namespace.ldap_sync_last_successful_update_at,
  --namespace.ldap_sync_last_sync_at,
  --namespace.lfs_enabled,
  --namespace.parent_id,
  --namespace.shared_runners_enabled,
  --namespace.shared_runners_minutes_limit,
  --namespace.extra_shared_runners_minutes_limit,
  --namespace.repository_size_limit,
  --namespace.does_require_two_factor_authentication,
  --namespace.two_factor_grace_period,
  --namespace.project_creation_level,
  --namespace.push_rule_id,
  --namespace.creator_id,
  --namespace.namespace_creator_is_blocked,
  --namespace.ultimate_parent_namespace_id,
  --namespace.gitlab_plan_id,
  --namespace.gitlab_plan_title,
  --namespace.gitlab_plan_is_paid,
  --namespace.dim_product_tier_id,
  --namespace.current_member_count,
  --namespace.current_project_count,
  --namespace.created_by,
  --namespace.updated_by,
  --namespace.model_created_date,
  --namespace.model_updated_date,
  --namespace.dbt_updated_at,
  --project.dbt_created_at,
  project.dim_project_id,
  --project.dim_namespace_id,
  --project.ultimate_parent_namespace_id,
  --project.dim_user_id_creator,
  --project.dim_date_id,
  --project.dim_product_tier_id_at_creation,
  --project.created_at,
  --project.updated_at,
  --project.last_activity_at,
  --project.visibility_level,
  --project.is_archived,
  --project.has_avatar,
  --project.project_star_count,
  --project.merge_requests_rebase_enabled,
  --project.import_type,
  --project.is_imported,
  --project.approvals_before_merge,
  --project.reset_approvals_on_push,
  --project.merge_requests_ff_only_enabled,
  --project.mirror,
  --project.mirror_user_id,
  --project.shared_runners_enabled,
  --project.build_allow_git_fetch,
  --project.build_timeout,
  --project.mirror_trigger_builds,
  --project.pending_delete,
  --project.public_builds,
  --project.last_repository_check_failed,
  --project.last_repository_check_at,
  --project.container_registry_enabled,
  --project.only_allow_merge_if_pipeline_succeeds,
  --project.has_external_issue_tracker,
  --project.repository_storage,
  --project.repository_read_only,
  --project.request_access_enabled,
  --project.has_external_wiki,
  --project.ci_config_path,
  --project.lfs_enabled,
  --project.only_allow_merge_if_all_discussions_are_resolved,
  --project.repository_size_limit,
  --project.printing_merge_request_link_enabled,
  --project.has_auto_canceling_pending_pipelines,
  --project.service_desk_enabled,
  --project.delete_error,
  --project.last_repository_updated_at,
  --project.storage_version,
  --project.resolve_outdated_diff_discussions,
  --project.disable_overriding_approvers_per_merge_request,
  --project.remote_mirror_available_overridden,
  --project.only_mirror_protected_branches,
  --project.pull_mirror_available_overridden,
  --project.mirror_overwrites_diverged_branches,
  --project.namespace_is_internal,
  --project.project_description,
  --project.project_import_source,
  --project.project_issues_template,
  --project.project_build_coverage_regex,
  --project.project_name,
  --project.project_path,
  --project.project_import_url,
  --project.project_merge_requests_template,
  --project.active_service_types_array,
  --project.is_learn_gitlab,
  --project.member_count,
  --project.created_by,
  --project.updated_by,
  --project.model_created_date,
  --project.model_updated_date,
  --project.dbt_updated_at,
  --operating_system.dbt_created_at,
  --operating_system.dim_behavior_operating_system_sk,
  --operating_system.os,
  --operating_system.os_name,
  --operating_system.os_manufacturer,
  --operating_system.os_timezone,
  operating_system.device_type,
  operating_system.is_device_mobile
  --operating_system.max_timestamp,
  --operating_system.created_by,
  --operating_system.updated_by,
  --operating_system.model_created_date,
  --operating_system.model_updated_date,
  --operating_system.dbt_updated_at,
  --operating_system.dbt_created_at
FROM structured_behavior
LEFT JOIN event
  ON structured_behavior.dim_behavior_event_sk = event.dim_behavior_event_sk
LEFT JOIN namespace
  ON structured_behavior.dim_namespace_id = namespace.dim_namespace_id
LEFT JOIN project
  ON structured_behavior.dim_project_id = project.dim_project_id
LEFT JOIN operating_system
  ON structured_behavior.dim_behavior_operating_system_sk = operating_system.dim_behavior_operating_system_sk
LEFT JOIN dates
  ON {{ get_date_id('structured_behavior.behavior_at') }} = dates.date_id