version: 2

sources:
  - name: omamori
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: omamori
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 5, period: hour}
      error_after: {count: 10, period: hour}
    tables:
      - name: entity_data_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/entity_data'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: mitigation_plan_entity_data_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/mitigation_plan_entity_data'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: mitigation_plans_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/mitigation_plans'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: rule_evaluation_matches_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/rule_evaluation_matches'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: rule_evaluations_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/rule_evaluations'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: tags_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/tags'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
      - name: users_external
        external:
          location: '@"{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}".omamori.omamori_load_parquet/users'
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYYMMDD')
