version: 2

models:

  - name: mart_team_member_directory
    description: '{{ doc("mart_team_member_directory") }}'
    data_tests:
      - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - employee_id
              - valid_from
    columns:
      - name: dim_team_member_sk
        description: A unique ID for each team member
        data_tests: 
          - not_null
      - name: dim_team_sk
        description: A unique ID for each team
      - name: employee_id
        description: Workday Employee Identification 
        data_tests: 
          - not_null
      - name: nationality
        description: Team member's nationality
        meta:
          masking_policy: analyst_people_sensitive
      - name: ethnicity
        description: Team member's ethnicity
        meta:
          masking_policy: analyst_people_sensitive
      - name: first_name
        description: Team member's first name
      - name: last_name
        description: Team member's last name
      - name: full_name
        description: Team member's full name
      - name: gender
        description: Team member's gender
        meta:
          masking_policy: analyst_people_sensitive
      - name: work_email
        description: Team member's work email
      - name: date_of_birth
        description: Team member's date of birth
        meta:
          masking_policy: analyst_people_sensitive
      - name: age
        description: Team member's age
        meta:
          masking_policy: analyst_people_sensitive
      - name: age_cohort
        description: Team member's age cohort
        meta:
          masking_policy: analyst_people_sensitive
      - name: cost_center
        description: Team member's cost center
      - name: gitlab_username
        description: Team member's gitlab username
      - name: country
        description: Team member's country
        meta:
          masking_policy: analyst_people_sensitive
      - name: region
        description: Team member's region
        meta:
          masking_policy: analyst_people_sensitive
      - name: region_modified
        description: Region modified for team members from the Americas. Team members are split into LATAM or NORAM
      - name: gender_region
        description: Team member's gender and region combined
        meta:
          masking_policy: analyst_people_sensitive
      - name: ethnicity_region
        description: Team member's ethnicity and region combined
        meta:
          masking_policy: analyst_people_sensitive
      - name: urg_group
        description: Team member's URG group
        meta:
          masking_policy: analyst_people_sensitive
      - name: urg_region
        description: Team member's URG region
        meta:
          masking_policy: analyst_people_sensitive
      - name: hire_date
        description: Team member's hire date
      - name: employee_type
        description: The employee type from the following list - Employee (PEO or Entity), Contractor (Independent, customer-to-customer or PEO), Intern, Consultant.
      - name: termination_date
        description: Team member's termination date
      - name: is_current_team_member
        description: Team member's team member status (are they a current team member or not)
      - name: is_rehire
        description: Team member's rehire flag
      - name: team_id
        description: A unique ID for each team from Workday
      - name: team_manager_name
        description: Team member's manager name
      - name: department
        description: Team member's department
      - name: division
        description: Team member's division
      - name: suporg
        description: Team member's Support Organization
      - name: job_code
        description: Team member's job code
      - name: position
        description: Team member's position
      - name: job_family
        description: Team member's job family
      - name: job_specialty_single
        description: Team member's job specialty
      - name: job_specialty_multi
        description: Team member's job specialty (multi-select)
      - name: management_level
        description: Team member's management level
      - name: job_grade
        description: Team member's job grade
      - name: entity
        description: Team member's entity
        meta:
          masking_policy: analyst_people_sensitive
      - name: valid_from
      - name: valid_to
      - name: is_current
