{{ config(
    materialized="incremental",
    unique_key="crm_opportunity_snapshot_id"
) }}

{{ simple_cte([
    ('fct_crm_opportunity_granular','wk_fct_crm_opportunity_7th_day_weekly_snapshot'),
    ('fct_crm_opportunity_aggregate','wk_fct_crm_opportunity_7th_day_weekly_snapshot_aggregate'),
    ('dim_crm_account','dim_crm_account_daily_snapshot'),
    ('dim_crm_user', 'wk_prep_crm_user_daily_snapshot'),
    ('dim_date', 'dim_date')
]) }},

unioned AS (

  SELECT 
    *,
    'granular' AS source
  FROM fct_crm_opportunity_granular
  WHERE is_current_snapshot_quarter

  UNION

  SELECT
    NULL AS crm_opportunity_snapshot_id,
    NULL AS dim_crm_opportunity_id,
    snapshot_id,
    dim_sales_qualified_source_id,
    dim_order_type_id,
    dim_order_type_live_id,
    dim_crm_user_hierarchy_sk,
    crm_user_business_unit,
    crm_user_sales_segment,
    crm_user_geo,
    crm_user_region,
    crm_user_area,
    crm_user_role_name,
    crm_user_role_level_1,
    crm_user_role_level_2,
    crm_user_role_level_3,
    crm_user_role_level_4,
    crm_user_role_level_5,
    crm_user_sales_segment_grouped,
    crm_user_sales_segment_region_grouped,
    NULL AS merged_crm_opportunity_id,
    NULL AS dim_crm_account_id,
    NULL AS dim_crm_person_id,
    NULL AS sfdc_contact_id,
    NULL AS record_type_id,
    NULL AS opportunity_name,
    NULL AS report_user_segment_geo_region_area_sqs_ot,
    NULL AS opp_owner_name,
    NULL AS sales_qualified_source_name,
    NULL AS order_type,
    NULL AS order_type_live,
    NULL AS order_type_grouped,
    NULL AS stage_name,
    NULL AS deal_path_name,
    NULL AS sales_type,
    snapshot_date,
    snapshot_month,
    snapshot_fiscal_year,
    snapshot_fiscal_quarter_name,
    snapshot_fiscal_quarter_date,
    snapshot_day_of_fiscal_quarter_normalised,
    snapshot_day_of_fiscal_year_normalised,
    NULL AS created_date,
    NULL AS created_date_id,
    NULL AS sales_accepted_date,
    NULL AS sales_accepted_date_id,
    NULL AS close_date,
    NULL AS close_date_id,
    NULL AS arr_created_date_id,
    NULL AS arr_created_date,
    NULL AS stage_0_pending_acceptance_date,
    NULL AS stage_0_pending_acceptance_date_id,
    NULL AS stage_1_discovery_date,
    NULL AS stage_1_discovery_date_id,
    NULL AS stage_2_scoping_date,
    NULL AS stage_2_scoping_date_id,
    NULL AS stage_3_technical_evaluation_date,
    NULL AS stage_3_technical_evaluation_date_id,
    NULL AS stage_4_proposal_date,
    NULL AS stage_4_proposal_date_id,
    NULL AS stage_5_negotiating_date,
    NULL AS stage_5_negotiating_date_id,
    NULL AS stage_6_awaiting_signature_date,
    NULL AS stage_6_awaiting_signature_date_id,
    NULL AS stage_6_closed_won_date,
    NULL AS stage_6_closed_won_date_id,
    NULL AS stage_6_closed_lost_date,
    NULL AS stage_6_closed_lost_date_id,
    NULL AS days_in_0_pending_acceptance,
    NULL AS days_in_1_discovery,
    NULL AS days_in_2_scoping,
    NULL AS days_in_3_technical_evaluation,
    NULL AS days_in_4_proposal,
    NULL AS days_in_5_negotiating,
    NULL AS subscription_start_date_id,
    NULL AS subscription_end_date_id,
    NULL AS sales_qualified_date_id,
    NULL AS last_activity_date,
    NULL AS last_activity_date_id,
    NULL AS sales_last_activity_date,
    NULL AS sales_last_activity_date_id,
    NULL AS technical_evaluation_date,
    NULL AS dim_crm_opp_owner_stamped_hierarchy_sk,
    NULL AS technical_evaluation_date_id,
    NULL AS ssp_id,
    NULL AS ga_client_id,
    NULL AS is_closed,
    NULL AS is_won,
    NULL AS is_refund,
    NULL AS is_downgrade,
    NULL AS is_swing_deal,
    NULL AS is_edu_oss,
    NULL AS is_web_portal_purchase,
    NULL AS fpa_master_bookings_flag,
    NULL AS is_sao,
    NULL AS is_sdr_sao,
    NULL AS is_net_arr_closed_deal,
    NULL AS is_new_logo_first_order,
    NULL AS is_net_arr_pipeline_created_combined,
    NULL AS is_win_rate_calc,
    NULL AS is_closed_won,
    NULL AS is_stage_1_plus,
    NULL AS is_stage_3_plus,
    NULL AS is_stage_4_plus,
    NULL AS is_lost,
    NULL AS is_open,
    NULL AS is_active,
    NULL AS is_credit,
    NULL AS is_renewal,
    NULL AS is_deleted,
    NULL AS is_excluded_from_pipeline_created_combined,
    NULL AS created_in_snapshot_quarter_deal_count,
    NULL AS is_duplicate,
    NULL AS is_contract_reset,
    NULL AS is_comp_new_logo_override,
    NULL AS is_eligible_open_pipeline_combined,
    NULL AS is_eligible_age_analysis_combined,
    NULL AS is_eligible_churn_contraction,
    NULL AS is_booked_net_arr,
    NULL AS is_abm_tier_sao,
    NULL AS is_abm_tier_closed_won,
    NULL AS primary_solution_architect,
    NULL AS product_details,
    NULL AS product_category,
    NULL AS intended_product_tier,
    NULL AS products_purchased,
    NULL AS growth_type,
    NULL AS opportunity_deal_size,
    NULL AS closed_buckets,
    NULL AS calculated_deal_size,
    NULL AS deal_size,
    NULL AS lead_source,
    NULL AS dr_partner_deal_type,
    NULL AS dr_partner_engagement,
    NULL AS partner_account,
    NULL AS dr_status,
    NULL AS dr_deal_id,
    NULL AS dr_primary_registration,
    NULL AS distributor,
    NULL AS influence_partner,
    NULL AS fulfillment_partner,
    NULL AS platform_partner,
    NULL AS partner_track,
    NULL AS resale_partner_track,
    NULL AS is_public_sector_opp,
    NULL AS is_registration_from_portal,
    NULL AS calculated_discount,
    NULL AS partner_discount,
    NULL AS partner_discount_calc,
    NULL AS comp_channel_neutral,
    created_arr,
    closed_won_opps,
    total_closed_opps,
    total_closed_net_arr,
    segment_order_type_iacv_to_net_arr_ratio,
    calculated_from_ratio_net_arr,
    net_arr,
    raw_net_arr,
    created_and_won_same_quarter_net_arr_combined,
    new_logo_count,
    amount,
    recurring_amount,
    true_up_amount,
    proserv_amount,
    other_non_recurring_amount,
    arr_basis,
    arr,
    count_crm_attribution_touchpoints,
    weighted_linear_iacv,
    count_campaigns,
    probability,
    days_in_sao,
    open_1plus_deal_count,
    open_3plus_deal_count,
    open_4plus_deal_count,
    booked_deal_count,
    churned_contraction_deal_count,
    open_1plus_net_arr,
    open_3plus_net_arr,
    open_4plus_net_arr,
    booked_net_arr,
    churned_contraction_net_arr,
    calculated_deal_count,
    booked_churned_contraction_deal_count,
    booked_churned_contraction_net_arr,
    renewal_amount,
    total_contract_value,
    days_in_stage,
    calculated_age_in_days,
    days_since_last_activity,
    pre_military_invasion_arr,
    won_arr_basis_for_clari,
    arr_basis_for_clari,
    forecasted_churn_for_clari,
    override_arr_basis_clari,
    vsa_start_date_net_arr,
    cycle_time_in_days_combined,
    NULL AS day_of_week,
    NULL AS first_day_of_week,
    NULL AS date_id,
    NULL AS fiscal_month_name_fy,
    NULL AS fiscal_quarter_name_fy,
    NULL AS first_day_of_fiscal_quarter,
    NULL AS first_day_of_fiscal_year,
    NULL AS last_day_of_week,
    NULL AS last_day_of_month,
    NULL AS last_day_of_fiscal_quarter,
    NULL AS last_day_of_fiscal_year,
    is_current_snapshot_quarter,
    'aggregate' AS source
  FROM fct_crm_opportunity_aggregate

),

final AS (


  SELECT

    unioned.crm_opportunity_snapshot_id,
    unioned.dim_crm_opportunity_id,
    unioned.snapshot_id,
    unioned.dim_sales_qualified_source_id,
    unioned.dim_order_type_id,
    unioned.dim_order_type_live_id,
    unioned.dim_crm_user_hierarchy_sk,
    unioned.crm_user_business_unit,
    unioned.crm_user_sales_segment,
    unioned.crm_user_geo,
    unioned.crm_user_region,
    unioned.crm_user_area,
    unioned.crm_user_role_name,
    unioned.crm_user_role_level_1,
    unioned.crm_user_role_level_2,
    unioned.crm_user_role_level_3,
    unioned.crm_user_role_level_4,
    unioned.crm_user_role_level_5,
    unioned.crm_user_sales_segment_grouped,
    unioned.crm_user_sales_segment_region_grouped,
    unioned.merged_crm_opportunity_id,
    unioned.dim_crm_account_id,
    unioned.dim_crm_person_id,
    unioned.sfdc_contact_id,
    unioned.record_type_id,
    unioned.opportunity_name,
    unioned.report_user_segment_geo_region_area_sqs_ot,
    unioned.opp_owner_name,
    unioned.sales_qualified_source_name,
    unioned.order_type,
    unioned.order_type_live,
    unioned.order_type_grouped,
    unioned.stage_name,
    unioned.deal_path_name,
    unioned.sales_type,
    unioned.snapshot_date,
    unioned.snapshot_month,
    unioned.snapshot_fiscal_year,
    unioned.snapshot_fiscal_quarter_name,
    unioned.snapshot_fiscal_quarter_date,
    unioned.snapshot_day_of_fiscal_quarter_normalised,
    unioned.snapshot_day_of_fiscal_year_normalised,

    
    unioned.days_in_0_pending_acceptance,
    unioned.days_in_1_discovery,
    unioned.days_in_2_scoping,
    unioned.days_in_3_technical_evaluation,
    unioned.days_in_4_proposal,
    unioned.days_in_5_negotiating,
    unioned.ssp_id,
    unioned.ga_client_id,
    unioned.is_closed,
    unioned.is_won,
    unioned.is_refund,
    unioned.is_downgrade,
    unioned.is_swing_deal,
    unioned.is_edu_oss,
    unioned.is_web_portal_purchase,
    unioned.fpa_master_bookings_flag,
    unioned.is_sao,
    unioned.is_sdr_sao,
    unioned.is_net_arr_closed_deal,
    unioned.is_new_logo_first_order,
    unioned.is_net_arr_pipeline_created_combined,
    unioned.is_win_rate_calc,
    unioned.is_closed_won,
    unioned.is_stage_1_plus,
    unioned.is_stage_3_plus,
    unioned.is_stage_4_plus,
    unioned.is_lost,
    unioned.is_open,
    unioned.is_active,
    unioned.is_credit,
    unioned.is_renewal,
    unioned.is_deleted,
    unioned.is_excluded_from_pipeline_created_combined,
    unioned.created_in_snapshot_quarter_deal_count,
    unioned.is_duplicate,
    unioned.is_contract_reset,
    unioned.is_comp_new_logo_override,
    unioned.is_eligible_open_pipeline_combined,
    unioned.is_eligible_age_analysis_combined,
    unioned.is_eligible_churn_contraction,
    unioned.is_booked_net_arr,
    unioned.is_abm_tier_sao,
    unioned.is_abm_tier_closed_won,
    unioned.primary_solution_architect,
    unioned.product_details,
    unioned.product_category,
    unioned.intended_product_tier,
    unioned.products_purchased,
    unioned.growth_type,
    unioned.opportunity_deal_size,
    unioned.closed_buckets,
    unioned.calculated_deal_size,
    unioned.deal_size,
    unioned.lead_source,
    unioned.dr_partner_deal_type,
    unioned.dr_partner_engagement,
    unioned.partner_account,
    unioned.dr_status,
    unioned.dr_deal_id,
    unioned.dr_primary_registration,
    unioned.distributor,
    unioned.influence_partner,
    unioned.fulfillment_partner,
    unioned.platform_partner,
    unioned.partner_track,
    unioned.resale_partner_track,
    unioned.is_public_sector_opp,
    unioned.is_registration_from_portal,
    unioned.calculated_discount,
    unioned.partner_discount,
    unioned.partner_discount_calc,
    unioned.comp_channel_neutral,

    dim_crm_account.dim_parent_crm_account_id,

    -- account fields
    dim_crm_account.crm_account_name,
    dim_crm_account.parent_crm_account_name,
    dim_crm_account.parent_crm_account_business_unit,
    dim_crm_account.parent_crm_account_sales_segment,
    dim_crm_account.parent_crm_account_geo,
    dim_crm_account.parent_crm_account_region,
    dim_crm_account.parent_crm_account_area,
    dim_crm_account.parent_crm_account_territory,
    dim_crm_account.parent_crm_account_role_type,
    dim_crm_account.parent_crm_account_max_family_employee,
    dim_crm_account.parent_crm_account_upa_country,
    dim_crm_account.parent_crm_account_upa_state,
    dim_crm_account.parent_crm_account_upa_city,
    dim_crm_account.parent_crm_account_upa_street,
    dim_crm_account.parent_crm_account_upa_postal_code,
    dim_crm_account.crm_account_employee_count,
    dim_crm_account.crm_account_gtm_strategy,
    dim_crm_account.crm_account_focus_account,
    dim_crm_account.crm_account_zi_technologies,
    dim_crm_account.is_jihu_account,
    -- crm owner/sales rep live fields
    opp_owner_live.crm_user_sales_segment,
    opp_owner_live.crm_user_sales_segment_grouped,
    opp_owner_live.crm_user_geo,
    opp_owner_live.crm_user_region,
    opp_owner_live.crm_user_area,
    opp_owner_live.crm_user_business_unit,
    {{ sales_segment_region_grouped('opp_owner_live.crm_user_sales_segment',
        'opp_owner_live.crm_user_geo', 'opp_owner_live.crm_user_region') }}
    AS crm_user_sales_segment_region_grouped,

    -- crm account owner/sales rep live fields
    account_owner_live.crm_user_sales_segment AS crm_account_user_sales_segment,
    account_owner_live.crm_user_sales_segment_grouped AS crm_account_user_sales_segment_grouped,
    account_owner_live.crm_user_geo AS crm_account_user_geo,
    account_owner_live.crm_user_region AS crm_account_user_region,
    account_owner_live.crm_user_area AS crm_account_user_area,
    {{ sales_segment_region_grouped('account_owner_live.crm_user_sales_segment',
        'account_owner_live.crm_user_geo', 'account_owner_live.crm_user_region') }}
    AS crm_account_user_sales_segment_region_grouped,

    
    LOWER(
      account_owner_live.crm_user_sales_segment
    ) AS account_owner_user_segment,
    LOWER(
      account_owner_live.crm_user_geo
    ) AS account_owner_user_geo,
    LOWER(
      account_owner_live.crm_user_region
    ) AS account_owner_user_region,
    LOWER(
      account_owner_live.crm_user_area
    ) AS account_owner_user_area,

    -- channel fields
    
    partner_account.crm_account_name AS partner_account_name,
    partner_account.gitlab_partner_program  AS partner_gitlab_program,
    fulfillment_partner.crm_account_name AS fulfillment_partner_name,

    -- Dates
    current_date.current_date_actual,
    current_date.current_fiscal_year,
    current_date.current_first_day_of_fiscal_year,
    current_date.current_fiscal_quarter_name_fy,
    current_date.current_first_day_of_month,
    current_date.current_first_day_of_fiscal_quarter,
    current_date.current_day_of_month,
    current_date.current_day_of_fiscal_quarter,
    current_date.current_day_of_fiscal_year,
    current_date.current_week_of_fiscal_quarter_normalised,
    created_date.date_actual                                        AS created_date,
    created_date.first_day_of_month                                 AS created_month,
    created_date.first_day_of_fiscal_quarter                        AS created_fiscal_quarter_date,
    created_date.fiscal_quarter_name_fy                             AS created_fiscal_quarter_name,
    created_date.fiscal_year                                        AS created_fiscal_year,
    sales_accepted_date.date_actual                                 AS sales_accepted_date,
    sales_accepted_date.first_day_of_month                          AS sales_accepted_month,
    sales_accepted_date.first_day_of_fiscal_quarter                 AS sales_accepted_fiscal_quarter_date,
    sales_accepted_date.fiscal_quarter_name_fy                      AS sales_accepted_fiscal_quarter_name,
    sales_accepted_date.fiscal_year                                 AS sales_accepted_fiscal_year,
    close_date.date_actual                                          AS close_date,
    close_date.first_day_of_month                                   AS close_month,
    close_date.first_day_of_fiscal_quarter                          AS close_fiscal_quarter_date,
    close_date.fiscal_quarter_name_fy                               AS close_fiscal_quarter_name,
    close_date.fiscal_year                                          AS close_fiscal_year,
    stage_0_pending_acceptance_date.date_actual                     AS stage_0_pending_acceptance_date,
    stage_0_pending_acceptance_date.first_day_of_month              AS stage_0_pending_acceptance_month,
    stage_0_pending_acceptance_date.first_day_of_fiscal_quarter     AS stage_0_pending_acceptance_fiscal_quarter_date,
    stage_0_pending_acceptance_date.fiscal_quarter_name_fy          AS stage_0_pending_acceptance_fiscal_quarter_name,
    stage_0_pending_acceptance_date.fiscal_year                     AS stage_0_pending_acceptance_fiscal_year,
    stage_1_discovery_date.date_actual                              AS stage_1_discovery_date,
    stage_1_discovery_date.first_day_of_month                       AS stage_1_discovery_month,
    stage_1_discovery_date.first_day_of_fiscal_quarter              AS stage_1_discovery_fiscal_quarter_date,
    stage_1_discovery_date.fiscal_quarter_name_fy                   AS stage_1_discovery_fiscal_quarter_name,
    stage_1_discovery_date.fiscal_year                              AS stage_1_discovery_fiscal_year,
    stage_2_scoping_date.date_actual                                AS stage_2_scoping_date,
    stage_2_scoping_date.first_day_of_month                         AS stage_2_scoping_month,
    stage_2_scoping_date.first_day_of_fiscal_quarter                AS stage_2_scoping_fiscal_quarter_date,
    stage_2_scoping_date.fiscal_quarter_name_fy                     AS stage_2_scoping_fiscal_quarter_name,
    stage_2_scoping_date.fiscal_year                                AS stage_2_scoping_fiscal_year,
    stage_3_technical_evaluation_date.date_actual                   AS stage_3_technical_evaluation_date,
    stage_3_technical_evaluation_date.first_day_of_month            AS stage_3_technical_evaluation_month,
    stage_3_technical_evaluation_date.first_day_of_fiscal_quarter   AS stage_3_technical_evaluation_fiscal_quarter_date,
    stage_3_technical_evaluation_date.fiscal_quarter_name_fy        AS stage_3_technical_evaluation_fiscal_quarter_name,
    stage_3_technical_evaluation_date.fiscal_year                   AS stage_3_technical_evaluation_fiscal_year,
    stage_4_proposal_date.date_actual                               AS stage_4_proposal_date,
    stage_4_proposal_date.first_day_of_month                        AS stage_4_proposal_month,
    stage_4_proposal_date.first_day_of_fiscal_quarter               AS stage_4_proposal_fiscal_quarter_date,
    stage_4_proposal_date.fiscal_quarter_name_fy                    AS stage_4_proposal_fiscal_quarter_name,
    stage_4_proposal_date.fiscal_year                               AS stage_4_proposal_fiscal_year,
    stage_5_negotiating_date.date_actual                            AS stage_5_negotiating_date,
    stage_5_negotiating_date.first_day_of_month                     AS stage_5_negotiating_month,
    stage_5_negotiating_date.first_day_of_fiscal_quarter            AS stage_5_negotiating_fiscal_quarter_date,
    stage_5_negotiating_date.fiscal_quarter_name_fy                 AS stage_5_negotiating_fiscal_quarter_name,
    stage_5_negotiating_date.fiscal_year                            AS stage_5_negotiating_fiscal_year,
    stage_6_awaiting_signature_date.date_actual                     AS stage_6_awaiting_signature_date,
    stage_6_awaiting_signature_date.date_actual                     AS stage_6_awaiting_signature_date_date, -- added to maintain workspace model temporarily 
    stage_6_awaiting_signature_date.first_day_of_month              AS stage_6_awaiting_signature_date_month,
    stage_6_awaiting_signature_date.first_day_of_fiscal_quarter     AS stage_6_awaiting_signature_date_fiscal_quarter_date,
    stage_6_awaiting_signature_date.fiscal_quarter_name_fy          AS stage_6_awaiting_signature_date_fiscal_quarter_name,
    stage_6_awaiting_signature_date.fiscal_year                     AS stage_6_awaiting_signature_date_fiscal_year,
    stage_6_closed_won_date.date_actual                             AS stage_6_closed_won_date,
    stage_6_closed_won_date.first_day_of_month                      AS stage_6_closed_won_month,
    stage_6_closed_won_date.first_day_of_fiscal_quarter             AS stage_6_closed_won_fiscal_quarter_date,
    stage_6_closed_won_date.fiscal_quarter_name_fy                  AS stage_6_closed_won_fiscal_quarter_name,
    stage_6_closed_won_date.fiscal_year                             AS stage_6_closed_won_fiscal_year,
    stage_6_closed_lost_date.date_actual                            AS stage_6_closed_lost_date,
    stage_6_closed_lost_date.first_day_of_month                     AS stage_6_closed_lost_month,
    stage_6_closed_lost_date.first_day_of_fiscal_quarter            AS stage_6_closed_lost_fiscal_quarter_date,
    stage_6_closed_lost_date.fiscal_quarter_name_fy                 AS stage_6_closed_lost_fiscal_quarter_name,
    stage_6_closed_lost_date.fiscal_year                            AS stage_6_closed_lost_fiscal_year,
    subscription_start_date.date_actual                             AS subscription_start_date,
    subscription_start_date.first_day_of_month                      AS subscription_start_month,
    subscription_start_date.first_day_of_fiscal_quarter             AS subscription_start_fiscal_quarter_date,
    subscription_start_date.fiscal_quarter_name_fy                  AS subscription_start_fiscal_quarter_name,
    subscription_start_date.fiscal_year                             AS subscription_start_fiscal_year,
    subscription_end_date.date_actual                               AS subscription_end_date,
    subscription_end_date.first_day_of_month                        AS subscription_end_month,
    subscription_end_date.first_day_of_fiscal_quarter               AS subscription_end_fiscal_quarter_date,
    subscription_end_date.fiscal_quarter_name_fy                    AS subscription_end_fiscal_quarter_name,
    subscription_end_date.fiscal_year                               AS subscription_end_fiscal_year,
    sales_qualified_date.date_actual                                AS sales_qualified_date,
    sales_qualified_date.first_day_of_month                         AS sales_qualified_month,
    sales_qualified_date.first_day_of_fiscal_quarter                AS sales_qualified_fiscal_quarter_date,
    sales_qualified_date.fiscal_quarter_name_fy                     AS sales_qualified_fiscal_quarter_name,
    sales_qualified_date.fiscal_year                                AS sales_qualified_fiscal_year,
    last_activity_date.date_actual                                  AS last_activity_date,
    last_activity_date.first_day_of_month                           AS last_activity_month,
    last_activity_date.first_day_of_fiscal_quarter                  AS last_activity_fiscal_quarter_date,
    last_activity_date.fiscal_quarter_name_fy                       AS last_activity_fiscal_quarter_name,
    last_activity_date.fiscal_year                                  AS last_activity_fiscal_year,
    sales_last_activity_date.date_actual                            AS sales_last_activity_date,
    sales_last_activity_date.first_day_of_month                     AS sales_last_activity_month,
    sales_last_activity_date.first_day_of_fiscal_quarter            AS sales_last_activity_fiscal_quarter_date,
    sales_last_activity_date.fiscal_quarter_name_fy                 AS sales_last_activity_fiscal_quarter_name,
    sales_last_activity_date.fiscal_year                            AS sales_last_activity_fiscal_year,
    technical_evaluation_date.date_actual                           AS technical_evaluation_date,
    technical_evaluation_date.first_day_of_month                    AS technical_evaluation_month,
    technical_evaluation_date.first_day_of_fiscal_quarter           AS technical_evaluation_fiscal_quarter_date,
    technical_evaluation_date.fiscal_quarter_name_fy                AS technical_evaluation_fiscal_quarter_name,
    technical_evaluation_date.fiscal_year                           AS technical_evaluation_fiscal_year,
    arr_created_date.date_actual                                    AS arr_created_date,
    arr_created_date.first_day_of_month                             AS arr_created_month,
    arr_created_date.first_day_of_fiscal_quarter                    AS arr_created_fiscal_quarter_date,
    arr_created_date.fiscal_quarter_name_fy                         AS arr_created_fiscal_quarter_name,
    arr_created_date.fiscal_year                                    AS arr_created_fiscal_year,
    arr_created_date.date_actual                                    AS pipeline_created_date,
    arr_created_date.first_day_of_month                             AS pipeline_created_month,
    arr_created_date.first_day_of_fiscal_quarter                    AS pipeline_created_fiscal_quarter_date,
    arr_created_date.fiscal_quarter_name_fy                         AS pipeline_created_fiscal_quarter_name,
    arr_created_date.fiscal_year                                    AS pipeline_created_fiscal_year,
    arr_created_date.date_actual                                    AS net_arr_created_date,
    arr_created_date.first_day_of_month                             AS net_arr_created_month,
    arr_created_date.first_day_of_fiscal_quarter                    AS net_arr_created_fiscal_quarter_date,
    arr_created_date.fiscal_quarter_name_fy                         AS net_arr_created_fiscal_quarter_name,
    arr_created_date.fiscal_year                                    AS net_arr_created_fiscal_year,
    dim_date.snapshot_day,
    dim_date.snapshot_day_name,
    dim_date.snapshot_fiscal_year,
    dim_date.snapshot_fiscal_quarter_name,
    dim_date.snapshot_fiscal_quarter_date,
    dim_date.snapshot_week_of_year,
    dim_date.snapshot_fiscal_quarter,
    dim_date.snapshot_month_name,
    dim_date.snapshot_first_day_of_month,
    dim_date.snapshot_last_day_of_month,
    dim_date.snapshot_first_day_of_year,
    dim_date.snapshot_last_day_of_year,
    dim_date.snapshot_first_day_of_quarter,
    dim_date.snapshot_last_day_of_quarter,
    dim_date.snapshot_first_day_of_fiscal_quarter,
    dim_date.snapshot_last_day_of_fiscal_quarter,
    dim_date.snapshot_first_day_of_fiscal_year,
    dim_date.snapshot_last_day_of_fiscal_year,
    dim_date.snapshot_week_of_fiscal_year,
    dim_date.snapshot_month_of_fiscal_year,
    dim_date.snapshot_quarter_name,
    dim_date.snapshot_fiscal_quarter_name_fy,
    dim_date.snapshot_fiscal_quarter_number_absolute,
    dim_date.snapshot_fiscal_month_name_fy,
    dim_date.snapshot_last_month_of_fiscal_quarter,
    dim_date.snapshot_last_month_of_fiscal_year,
    dim_date.snapshot_days_in_month_count,
    dim_date.snapshot_week_of_month_normalised,
    dim_date.snapshot_week_of_fiscal_quarter_normalised,
        unioned.created_arr,
    unioned.closed_won_opps,
    unioned.total_closed_opps,
    unioned.total_closed_net_arr,
    unioned.segment_order_type_iacv_to_net_arr_ratio,
    unioned.calculated_from_ratio_net_arr,
    unioned.net_arr,
    unioned.raw_net_arr,
    unioned.created_and_won_same_quarter_net_arr_combined,
    unioned.new_logo_count,
    unioned.amount,
    unioned.recurring_amount,
    unioned.true_up_amount,
    unioned.proserv_amount,
    unioned.other_non_recurring_amount,
    unioned.arr_basis,
    unioned.arr,
    unioned.count_crm_attribution_touchpoints,
    unioned.weighted_linear_iacv,
    unioned.count_campaigns,
    unioned.probability,
    unioned.days_in_sao,
    unioned.open_1plus_deal_count,
    unioned.open_3plus_deal_count,
    unioned.open_4plus_deal_count,
    unioned.booked_deal_count,
    unioned.churned_contraction_deal_count,
    unioned.open_1plus_net_arr,
    unioned.open_3plus_net_arr,
    unioned.open_4plus_net_arr,
    unioned.booked_net_arr,
    unioned.churned_contraction_net_arr,
    unioned.calculated_deal_count,
    unioned.booked_churned_contraction_deal_count,
    unioned.booked_churned_contraction_net_arr,
    unioned.renewal_amount,
    unioned.total_contract_value,
    unioned.days_in_stage,
    unioned.calculated_age_in_days,
    unioned.days_since_last_activity,
    unioned.pre_military_invasion_arr,
    unioned.won_arr_basis_for_clari,
    unioned.arr_basis_for_clari,
    unioned.forecasted_churn_for_clari,
    unioned.override_arr_basis_clari,
    unioned.vsa_start_date_net_arr,
    unioned.cycle_time_in_days_combined,
    unioned.day_of_week,
    unioned.first_day_of_week,
    unioned.date_id,
    unioned.fiscal_month_name_fy,
    unioned.fiscal_quarter_name_fy,
    unioned.first_day_of_fiscal_quarter,
    unioned.first_day_of_fiscal_year,
    unioned.last_day_of_week,
    unioned.last_day_of_month,
    unioned.last_day_of_fiscal_quarter,
    unioned.last_day_of_fiscal_year,
    unioned.is_current_snapshot_quarter,
    source

  FROM unioned
  LEFT JOIN dim_crm_account
    ON unioned.dim_crm_account_id = dim_crm_account.dim_crm_account_id
      AND unioned.snapshot_id = dim_crm_account.snapshot_id
  LEFT JOIN dim_crm_user AS opp_owner_live
    ON unioned.dim_crm_user_id = opp_owner_live.dim_crm_user_id
      AND unioned.snapshot_id = opp_owner_live.snapshot_id
  LEFT JOIN dim_crm_user AS account_owner_live
    ON dim_crm_account.dim_crm_user_id = account_owner_live.dim_crm_user_id
      AND dim_crm_account.snapshot_id = account_owner_live.snapshot_id
  LEFT JOIN dim_date 
    ON unioned.snapshot_date = dim_date.date_actual
  LEFT JOIN dim_date created_date
    ON unioned.created_date = created_date.date_actual
  LEFT JOIN dim_date sales_accepted_date
    ON unioned.sales_accepted_date = sales_accepted_date.date_actual
  LEFT JOIN dim_date close_date
    ON unioned.close_date = close_date.date_actual
  LEFT JOIN dim_date stage_0_pending_acceptance_date
    ON unioned.stage_0_pending_acceptance_date = stage_0_pending_acceptance_date.date_actual
  LEFT JOIN dim_date stage_1_discovery_date
    ON unioned.stage_1_discovery_date = stage_1_discovery_date.date_actual
  LEFT JOIN dim_date stage_2_scoping_date
    ON unioned.stage_2_scoping_date = stage_2_scoping_date.date_actual
  LEFT JOIN dim_date stage_3_technical_evaluation_date
    ON unioned.stage_3_technical_evaluation_date = stage_3_technical_evaluation_date.date_actual
  LEFT JOIN dim_date stage_4_proposal_date
    ON unioned.stage_4_proposal_date = stage_4_proposal_date.date_actual
  LEFT JOIN dim_date stage_5_negotiating_date
    ON unioned.stage_5_negotiating_date = stage_5_negotiating_date.date_actual
  LEFT JOIN dim_date stage_6_awaiting_signature_date
      ON unioned.stage_6_awaiting_signature_date_id = stage_6_awaiting_signature_date.date_id
  LEFT JOIN dim_date stage_6_closed_won_date
    ON unioned.stage_6_closed_won_date = stage_6_closed_won_date.date_actual
  LEFT JOIN dim_date stage_6_closed_lost_date
    ON unioned.stage_6_closed_lost_date = stage_6_closed_lost_date.date_actual
  LEFT JOIN dim_date subscription_start_date
    ON unioned.subscription_start_date = subscription_start_date.date_actual
  LEFT JOIN dim_date subscription_end_date
    ON unioned.subscription_end_date = subscription_end_date.date_actual
  LEFT JOIN dim_date sales_qualified_date
    ON unioned.sales_qualified_date = sales_qualified_date.date_actual
  LEFT JOIN dim_date last_activity_date
    ON unioned.last_activity_date = last_activity_date.date_actual
  LEFT JOIN dim_date sales_last_activity_date
    ON unioned.sales_last_activity_date = sales_last_activity_date.date_actual
  LEFT JOIN dim_date technical_evaluation_date
    ON unioned.technical_evaluation_date = technical_evaluation_date.date_actual
  LEFT JOIN dim_date arr_created_date 
    ON unioned.arr_created_date = arr_created_date.date_actual
  LEFT JOIN dim_crm_account AS partner_account
    ON unioned.partner_account = partner_account.dim_crm_account_id
      AND unioned.snapshot_id = partner_account.snapshot_id 
  LEFT JOIN dim_crm_account AS fulfillment_partner
    ON unioned.fulfillment_partner = fulfillment_partner.dim_crm_account_id
      AND unioned.snapshot_id = fulfillment_partner.snapshot_id
  {% if is_incremental() %}
  
  WHERE unioned.snapshot_date > (SELECT MAX(snapshot_date) FROM {{this}})

  {% endif %}


)

SELECT * 
FROM final