WITH day_5th_snapshot AS (

  SELECT * 
  FROM {{ ref('wk_fct_targets_actuals_5th_day_weekly_snapshot') }}

),

aggregate_data AS (

  SELECT
    actuals_targets_daily_pk,
    dim_sales_qualified_source_id,
    dim_order_type_id,
    dim_crm_user_hierarchy_sk,

     --dates
    snapshot_date,
    date_day,
    day_name,
    month_actual,
    year_actual,
    quarter_actual,
    day_of_week,
    first_day_of_week,
    week_of_year,
    day_of_month,
    day_of_quarter,
    day_of_year,
    fiscal_year,
    fiscal_quarter,
    day_of_fiscal_quarter,
    day_of_fiscal_year,
    month_name,
    first_day_of_month,
    last_day_of_month,
    first_day_of_year,
    last_day_of_year,
    first_day_of_quarter,
    last_day_of_quarter,
    first_day_of_fiscal_quarter,
    last_day_of_fiscal_quarter,
    first_day_of_fiscal_year,
    last_day_of_fiscal_year,
    week_of_fiscal_year,
    month_of_fiscal_year,
    last_day_of_week,
    quarter_name,
    fiscal_quarter_name,
    fiscal_quarter_name_fy,
    fiscal_quarter_number_absolute,
    fiscal_month_name,
    fiscal_month_name_fy,
    last_month_of_fiscal_quarter,
    last_month_of_fiscal_year,
    week_of_month_normalised,
    day_of_fiscal_quarter_normalised,
    week_of_fiscal_quarter_normalised,
    day_of_fiscal_year_normalised,
    current_date_actual,
    current_fiscal_year,
    current_first_day_of_fiscal_year,
    current_fiscal_quarter_name_fy,
    current_first_day_of_month,
    current_first_day_of_fiscal_quarter,
    current_day_of_month,
    current_day_of_fiscal_quarter,
    current_day_of_fiscal_year,

    -- Targets
    deals_daily_target,
    deals_monthly_target,
    deals_wtd_target,
    deals_mtd_target,
    deals_qtd_target,
    deals_ytd_target,
    mql_daily_target,
    mql_monthly_target,
    mql_wtd_target,
    mql_mtd_target,
    mql_qtd_target,
    mql_ytd_target,
    net_arr_daily_target,
    net_arr_monthly_target,
    net_arr_wtd_target,
    net_arr_mtd_target,
    net_arr_qtd_target,
    net_arr_ytd_target,
    net_arr_company_daily_target,
    net_arr_company_monthly_target,
    net_arr_company_wtd_target,
    net_arr_company_mtd_target,
    net_arr_company_qtd_target,
    net_arr_company_ytd_target,
    net_arr_pipeline_created_daily_target,
    net_arr_pipeline_created_monthly_target,
    net_arr_pipeline_created_wtd_target,
    net_arr_pipeline_created_mtd_target,
    net_arr_pipeline_created_qtd_target,
    net_arr_pipeline_created_ytd_target,
    new_logos_daily_target,
    new_logos_monthly_target,
    new_logos_wtd_target,
    new_logos_mtd_target,
    new_logos_qtd_target,
    new_logos_ytd_target,
    stage_1_opportunities_daily_target,
    stage_1_opportunities_monthly_target,
    stage_1_opportunities_wtd_target,
    stage_1_opportunities_mtd_target,
    stage_1_opportunities_qtd_target,
    stage_1_opportunities_ytd_target,
    total_closed_daily_target,
    total_closed_monthly_target,
    total_closed_wtd_target,
    total_closed_mtd_target,
    total_closed_qtd_target,
    total_closed_ytd_target,
    trials_daily_target,
    trials_monthly_target,
    trials_wtd_target,
    trials_mtd_target,
    trials_qtd_target,
    trials_ytd_target
  FROM day_5th_snapshot
  GROUP BY ALL

)

SELECT * 
FROM aggregate_data
ORDER BY snapshot_date DESC
