WITH day_5th_snapshot AS (

  SELECT * 
  FROM {{ ref('wk_fct_targets_actuals_5th_day_weekly_snapshot') }}

),

aggregate_data AS (

  SELECT
    actuals_targets_daily_pk,
    dim_sales_qualified_source_id,
    dim_order_type_id,
    dim_crm_user_hierarchy_sk,

     --dates
    snapshot_date,
    date_day,
    day_name,
    month_actual,
    year_actual,
    quarter_actual,
    day_of_week,
    first_day_of_week,
    week_of_year,
    day_of_month,
    day_of_quarter,
    day_of_year,
    fiscal_year,
    fiscal_quarter,
    day_of_fiscal_quarter,
    day_of_fiscal_year,
    month_name,
    first_day_of_month,
    last_day_of_month,
    first_day_of_year,
    last_day_of_year,
    first_day_of_quarter,
    last_day_of_quarter,
    first_day_of_fiscal_quarter,
    last_day_of_fiscal_quarter,
    first_day_of_fiscal_year,
    last_day_of_fiscal_year,
    week_of_fiscal_year,
    month_of_fiscal_year,
    last_day_of_week,
    quarter_name,
    fiscal_quarter_name,
    fiscal_quarter_name_fy,
    fiscal_quarter_number_absolute,
    fiscal_month_name,
    fiscal_month_name_fy,
    last_month_of_fiscal_quarter,
    last_month_of_fiscal_year,
    week_of_month_normalised,
    day_of_fiscal_quarter_normalised,
    week_of_fiscal_quarter_normalised,
    day_of_fiscal_year_normalised,
    current_date_actual,
    current_fiscal_year,
    current_first_day_of_fiscal_year,
    current_fiscal_quarter_name_fy,
    current_first_day_of_month,
    current_first_day_of_fiscal_quarter,
    current_day_of_month,
    current_day_of_fiscal_quarter,
    current_day_of_fiscal_year,

    -- Additive fields
    SUM(iacv)                                        AS iacv,
    SUM(net_iacv)                                    AS net_iacv,
    SUM(segment_order_type_iacv_to_net_arr_ratio)    AS segment_order_type_iacv_to_net_arr_ratio,
    SUM(calculated_from_ratio_net_arr)               AS calculated_from_ratio_net_arr,
    SUM(net_arr)                                     AS net_arr,
    SUM(raw_net_arr)                                 AS raw_net_arr,
    SUM(created_and_won_same_quarter_net_arr_combined) AS created_and_won_same_quarter_net_arr_combined,
    SUM(new_logo_count)                              AS new_logo_count,
    SUM(amount)                                      AS amount,
    SUM(recurring_amount)                            AS recurring_amount,
    SUM(true_up_amount)                              AS true_up_amount,
    SUM(proserv_amount)                              AS proserv_amount,
    SUM(other_non_recurring_amount)                  AS other_non_recurring_amount,
    SUM(arr_basis)                                   AS arr_basis,
    SUM(arr)                                         AS arr,
    SUM(count_crm_attribution_touchpoints)           AS count_crm_attribution_touchpoints,
    SUM(weighted_linear_iacv)                        AS weighted_linear_iacv,
    SUM(count_campaigns)                             AS count_campaigns,
    SUM(probability)                                 AS probability,
    SUM(days_in_sao)                                 AS days_in_sao,
    SUM(open_1plus_deal_count)                       AS open_1plus_deal_count,
    SUM(open_3plus_deal_count)                       AS open_3plus_deal_count,
    SUM(open_4plus_deal_count)                       AS open_4plus_deal_count,
    SUM(booked_deal_count)                           AS booked_deal_count,
    SUM(churned_contraction_deal_count)              AS churned_contraction_deal_count,
    SUM(open_1plus_net_arr)                          AS open_1plus_net_arr,
    SUM(open_3plus_net_arr)                          AS open_3plus_net_arr,
    SUM(open_4plus_net_arr)                          AS open_4plus_net_arr,
    SUM(booked_net_arr)                              AS booked_net_arr,
    SUM(churned_contraction_net_arr)                 AS churned_contraction_net_arr,
    SUM(calculated_deal_count)                       AS calculated_deal_count,
    SUM(booked_churned_contraction_deal_count)       AS booked_churned_contraction_deal_count,
    SUM(booked_churned_contraction_net_arr)          AS booked_churned_contraction_net_arr,
    SUM(renewal_amount)                              AS renewal_amount,
    SUM(total_contract_value)                        AS total_contract_value,
    SUM(days_in_stage)                               AS days_in_stage,
    SUM(calculated_age_in_days)                      AS calculated_age_in_days,
    SUM(days_since_last_activity)                    AS days_since_last_activity,
    SUM(pre_military_invasion_arr)                   AS pre_military_invasion_arr,
    SUM(won_arr_basis_for_clari)                     AS won_arr_basis_for_clari,
    SUM(arr_basis_for_clari)                         AS arr_basis_for_clari,
    SUM(forecasted_churn_for_clari)                  AS forecasted_churn_for_clari,
    SUM(override_arr_basis_clari)                    AS override_arr_basis_clari,
    SUM(vsa_start_date_net_arr)                      AS vsa_start_date_net_arr,
    SUM(cycle_time_in_days_combined)                 AS cycle_time_in_days_combined,

    -- Targets
    SUM(deals_daily_target)                          AS deals_daily_target,
    SUM(deals_monthly_target)                        AS deals_monthly_target,
    SUM(deals_wtd_target)                            AS deals_wtd_target,
    SUM(deals_mtd_target)                            AS deals_mtd_target,
    SUM(deals_qtd_target)                            AS deals_qtd_target,
    SUM(deals_ytd_target)                            AS deals_ytd_target,
    SUM(mql_daily_target)                            AS mql_daily_target,
    SUM(mql_monthly_target)                          AS mql_monthly_target,
    SUM(mql_wtd_target)                              AS mql_wtd_target,
    SUM(mql_mtd_target)                              AS mql_mtd_target,
    SUM(mql_qtd_target)                              AS mql_qtd_target,
    SUM(mql_ytd_target)                              AS mql_ytd_target,
    SUM(net_arr_daily_target)                        AS net_arr_daily_target,
    SUM(net_arr_monthly_target)                      AS net_arr_monthly_target,
    SUM(net_arr_wtd_target)                          AS net_arr_wtd_target,
    SUM(net_arr_mtd_target)                          AS net_arr_mtd_target,
    SUM(net_arr_qtd_target)                          AS net_arr_qtd_target,
    SUM(net_arr_ytd_target)                          AS net_arr_ytd_target,
    SUM(net_arr_company_daily_target)                AS net_arr_company_daily_target,
    SUM(net_arr_company_monthly_target)              AS net_arr_company_monthly_target,
    SUM(net_arr_company_wtd_target)                  AS net_arr_company_wtd_target,
    SUM(net_arr_company_mtd_target)                  AS net_arr_company_mtd_target,
    SUM(net_arr_company_qtd_target)                  AS net_arr_company_qtd_target,
    SUM(net_arr_company_ytd_target)                  AS net_arr_company_ytd_target,
    SUM(net_arr_pipeline_created_daily_target)       AS net_arr_pipeline_created_daily_target,
    SUM(net_arr_pipeline_created_monthly_target)     AS net_arr_pipeline_created_monthly_target,
    SUM(net_arr_pipeline_created_wtd_target)         AS net_arr_pipeline_created_wtd_target,
    SUM(net_arr_pipeline_created_mtd_target)         AS net_arr_pipeline_created_mtd_target,
    SUM(net_arr_pipeline_created_qtd_target)         AS net_arr_pipeline_created_qtd_target,
    SUM(net_arr_pipeline_created_ytd_target)         AS net_arr_pipeline_created_ytd_target,
    SUM(new_logos_daily_target)                      AS new_logos_daily_target,
    SUM(new_logos_monthly_target)                    AS new_logos_monthly_target,
    SUM(new_logos_wtd_target)                        AS new_logos_wtd_target,
    SUM(new_logos_mtd_target)                        AS new_logos_mtd_target,
    SUM(new_logos_qtd_target)                        AS new_logos_qtd_target,
    SUM(new_logos_ytd_target)                        AS new_logos_ytd_target,
    SUM(stage_1_opportunities_daily_target)          AS stage_1_opportunities_daily_target,
    SUM(stage_1_opportunities_monthly_target)        AS stage_1_opportunities_monthly_target,
    SUM(stage_1_opportunities_wtd_target)            AS stage_1_opportunities_wtd_target,
    SUM(stage_1_opportunities_mtd_target)            AS stage_1_opportunities_mtd_target,
    SUM(stage_1_opportunities_qtd_target)            AS stage_1_opportunities_qtd_target,
    SUM(stage_1_opportunities_ytd_target)            AS stage_1_opportunities_ytd_target,
    SUM(total_closed_daily_target)                   AS total_closed_daily_target,
    SUM(total_closed_monthly_target)                 AS total_closed_monthly_target,
    SUM(total_closed_wtd_target)                     AS total_closed_wtd_target,
    SUM(total_closed_mtd_target)                     AS total_closed_mtd_target,
    SUM(total_closed_qtd_target)                     AS total_closed_qtd_target,
    SUM(total_closed_ytd_target)                     AS total_closed_ytd_target,
    SUM(trials_daily_target)                         AS trials_daily_target,
    SUM(trials_monthly_target)                       AS trials_monthly_target,
    SUM(trials_wtd_target)                           AS trials_wtd_target,
    SUM(trials_mtd_target)                           AS trials_mtd_target,
    SUM(trials_qtd_target)                           AS trials_qtd_target,
    SUM(trials_ytd_target)                           AS trials_ytd_target
  FROM day_5th_snapshot
  GROUP BY ALL

)

SELECT * 
FROM aggregate_data
ORDER BY snapshot_date DESC
