{{ config(
    materialized='view',
    database=env_var('SNOWFLAKE_PREP_DATABASE'),
    schema='container_registry'
) }}

WITH static_union AS (
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_01"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_02"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_03"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_04"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_05"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_06"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_07"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_08"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_09"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_10"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_11"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_12"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_13"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_14"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_15"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_16"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_17"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_18"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_19"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_20"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_21"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_22"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_23"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_24"
  
  UNION ALL
  SELECT *
  FROM "RAW"."CONTAINER_REGISTRY"."JOINED_2022_09_25"
)

SELECT *
FROM static_union