WITH source AS (

    SELECT *
    FROM {{ source('xactly', 'xc_commission') }}

), renamed AS (

    SELECT

      commission_id::FLOAT                          AS commission_id,
      version::FLOAT                                AS version,
      name::VARCHAR                                 AS name,
      is_active::VARCHAR                            AS is_active,
      amount::FLOAT                                  AS amount,
      amount_unit_type_id::FLOAT                     AS amount_unit_type_id,
      amount_display_symbol::VARCHAR                 AS amount_display_symbol,
      period_id::VARCHAR                             AS period_id,
      period_name::VARCHAR                           AS period_name,
      participant_id::FLOAT                          AS participant_id,
      participant_name::VARCHAR                      AS participant_name,
      position_id::FLOAT                             AS position_id,
      position_name::VARCHAR                         AS position_name,
      credit_id::FLOAT                               AS credit_id,
      credit_name::VARCHAR                           AS credit_name,
      order_item_id::FLOAT                           AS order_item_id,
      item_code::VARCHAR                             AS item_code,
      order_code::VARCHAR                            AS order_code,
      rule_id::FLOAT                                 AS rule_id,
      rule_name::VARCHAR                             AS rule_name,
      is_held::VARCHAR                               AS is_held,
      release_date::VARCHAR                          AS release_date,
      rate_amount::FLOAT                             AS rate_amount,
      rate_amount_unit_type_id::FLOAT                AS rate_amount_unit_type_id,
      rate_amount_display_symbol::VARCHAR            AS rate_amount_display_symbol,
      earning_group_id::FLOAT                        AS earning_group_id,
      earning_group_name::VARCHAR                    AS earning_group_name,
      reason_code_id::FLOAT                          AS reason_code_id,
      reason_code_name::VARCHAR                      AS reason_code_name,
      rate_table_id::FLOAT                           AS rate_table_id,
      rate_table_name::VARCHAR                       AS rate_table_name,
      quota_id::FLOAT                                AS quota_id,
      quota_name::VARCHAR                            AS quota_name,
      quota_period_type_id::FLOAT                    AS quota_period_type_id,
      quota_period_type_name::VARCHAR                AS quota_period_type_name,
      measure_value::FLOAT                           AS measure_value,
      measure_value_unit_type_id::FLOAT              AS measure_value_unit_type_id,
      attainment_value::FLOAT                        AS attainment_value,
      attainment_value_unit_type_id::FLOAT           AS attainment_value_unit_type_id,
      entry_number::FLOAT                            AS entry_number,
      is_processed::VARCHAR                          AS is_processed,
      credit_unit_type_id::FLOAT                     AS credit_unit_type_id,
      credit_amount::FLOAT                           AS credit_amount,
      is_credit_apply::VARCHAR                       AS is_credit_apply,
      payment_fx::VARCHAR                            AS payment_fx,
      trans_id::FLOAT                                AS trans_id,
      product_id::FLOAT                              AS product_id,
      product_name::VARCHAR                          AS product_name,
      customer_id::FLOAT                             AS customer_id,
      customer_name::VARCHAR                         AS customer_name,
      geography_id::FLOAT                            AS geography_id,
      geography_name::VARCHAR                        AS geography_name,
      ever_on_hold::VARCHAR                          AS ever_on_hold,
      release_group_id::FLOAT                        AS release_group_id,
      estimated_rel_date::VARCHAR                    AS estimated_rel_date,
      business_group_id::FLOAT                       AS business_group_id,
      source::VARCHAR                                AS source,
      released_amount::FLOAT                         AS released_amount,
      held_amount::FLOAT                             AS held_amount,
      run_id::FLOAT                                  AS run_id,
      incentive_date::VARCHAR                        AS incentive_date,
      eff_participant_id::FLOAT                      AS eff_participant_id,
      eff_position_id::FLOAT                         AS eff_position_id,
      plan_id::FLOAT                                 AS plan_id,
      plan_name::VARCHAR                             AS plan_name,
      credit_type_id::FLOAT                          AS credit_type_id,
      roll_measure_value::FLOAT                      AS roll_measure_value,
      roll_attainment_value::FLOAT                   AS roll_attainment_value,
      credit_applied::FLOAT                          AS credit_applied,
      rate_table_tier::FLOAT                         AS rate_table_tier,
      created_date::VARCHAR                          AS created_date,
      created_by_id::FLOAT                           AS created_by_id,
      created_by_name::VARCHAR                       AS created_by_name,
      modified_date::VARCHAR                         AS modified_date,
      modified_by_id::FLOAT                          AS modified_by_id,
      modified_by_name::VARCHAR                      AS modified_by_name,
      pending_commission_amount::FLOAT               AS pending_commission_amount,
      calculated_rate::FLOAT                         AS calculated_rate,
      rolling_incentive_attainment::FLOAT            AS rolling_incentive_attainment,
      incentive_attainment::FLOAT                    AS incentive_attainment,
      pt_achieved_percentage::FLOAT                  AS pt_achieved_percentage,
      applied_credit_amount::FLOAT                   AS applied_credit_amount,
      ever_on_pending::VARCHAR                       AS ever_on_pending,
      is_pending::VARCHAR                            AS is_pending,
      attainment_measure_hash::VARCHAR               AS attainment_measure_hash,
      paycurve_version_id::VARCHAR                   AS paycurve_version_id,
      paycurve_name::VARCHAR                         AS paycurve_name,
      rate_type::FLOAT                               AS rate_type
    FROM source

)

SELECT *
FROM renamed