version: 2

models:
  - name: rpt_duo_pro_license_utilization_monthly
    description: Workspace model for reporting on monthly Duo Pro seat utilization. Metric nuances described in column descriptions.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - reporting_month
            - dim_crm_account_id
            - product_deployment
            - paired_tier
    columns:
      - name: reporting_month
        description: Month of reported seats associated with Duo Pro subscription and usage behavior.
      - name: subscription_name
        description: '{{ doc("subscription_name") }}'
      - name: dim_subscription_id
        description: Identifier to join on 
      - name: crm_account_name
        description: '{{ doc("crm_account_name") }}'
      - name: dim_crm_account_id
        description: '{{ doc("dim_crm_account_id") }}'
      - name: dim_parent_crm_account_id
        description: '{{ doc("dim_parent_crm_account_id") }}'
      - name: product_deployment
        description: Using the deployment listed in product_rate_plan_name from mart_arr and renaming 'SaaS' to 'Gitlab.com' for clarity. 
      - name: add_on_name
        description: Currently only includes Duo Pro.
      - name: paired_tier
        description: Tier or tiers associated with the Duo Pro Add On purchase with reported revenue in the same month that Duo Pro revenue is reported within mart_arr.
      - name: is_product_entity_associated_w_subscription
        description: FALSE if installation or namespace idenitfier cannot be mapped to subscription.
      - name: major_minor_version_id
        description: Latest major_minor_version_id reported for SM or Dedicated installation within a month. Gitlab.com deployments are always up to date and managed by the internal GitLab team.
      - name: paid_duo_pro_seats
        description: quantity associated with Duo Pro subscription from mart_arr within a given reporting month.
      - name: count_seats_assigned
        description: Number of users assigned to use Duo Pro by the account admin within a paid Gitlab.com account. Given that admins can re-assign purchased Duo Pro seats to different users during the course of time, gitlab_dotcom_subscription_user_add_on_assignments can have more user assignments than its purchase quantity (per purchase). i.e. The data source will have records for both old users & new/replaced users. We can only identify valid users once per month using PGP_IS_DELETED. Until this process runs, the assignment rate for some subscriptions can be greater than 100%. 
      - name: chat_active_users
        description: Calculation utilizes request_duo_chat_response in mart_behavior_structured_event, a snowplow data source for Gitlab.com chat utilization and redis_hll_counters.count_distinct_user_id_from_request_duo_chat_response_monthly a service ping data source for SM and Dedicated chat utilization. redis_hll_counters.count_distinct_user_id_from_request_duo_chat_response_monthly was implemented in GitLab version 16.11. To only include SM & Dedicated accounts eligible to report on this metric, filter to major_minor_version_id >= 1611. Array of namespaces that enabled event to occur are used to map the namespace to a subscription for GitLab.com deployments.
      - name: code_suggestions_active_users
        description: Calculation utilizes event_action = 'suggestion_requested' and app_id = 'gitlab_ai_gateway' from mart_behavior_structured_event_code_suggestion for all Deployment types. All ultimate_parent_namespace_ids and dim_installation_ids captured per event are flattened from their array format and joined to Duo Pro subscription data to achieve a utilization match. These entities captured represent how the the usage of code suggestions is enabled as opposed to WHERE code suggestion requests occurred. 
      - name: max_duo_pro_active_users
        description: Because chat and code suggestions capture different user identifiers, an overall unique count cannot be calculated. This calculation takes the max count of users using code suggestions or chat as opposed to the total unique count of users. In the future a total unique count should be possible once a standard Cloud Connector event tracking methodology is available.
      - name: pct_usage_seat_utilization
        description: max_duo_pro_active_users / paid_duo_pro_seats
      - name: pct_assignment_seat_utilization
        description: number_of_seats_assigned / paid_duo_pro_seats This metric will equal 0 for all SM and Dedicated deployments sinced assigned seats are only captured for Gitlab.com accounts.
      - name: standard_pct_usage_seat_utilization
        description: max_duo_pro_active_users / paid_duo_pro_seats Result cannot exceed 100%.
      - name: standard_pct_assignment_seat_utilization
        description: number_of_seats_assigned / paid_duo_pro_seats Result cannot exceed 100%.
