version: 2

models:
    - name: thanos_stage_group_error_budget_availability_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_seconds_spent_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_seconds_remaining_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_total_haproxy_bytes_out
      columns:
        - name: metric_backend
        - name: metric_created_at
        - name: metric_value
          tests:
              - not_null
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_completeness_source
      columns:
        - name: metric_time_stamp
        - name: metric_value
          tests:
              - not_null
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_daily_slas_source
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - metric_query
              - metric_created_at
              - metric_value
      columns:
        - name: metric_query
          description: string, query selector
        - name: metric_env
          description: string, environment selector, can be gprd or ops
        - name: metric_environment
          description: string, environment selector, gprd only
        - name: metric_monitor
          description: string, monitor selector
        - name: metric_ruler_cluster
          description: string, thanos or null. name of cluster called
        - name: metric_sla_type
          description: string, selector for calculation mode
        - name: metric_stage
          description: string, stage 
        - name: metric_created_at
          description: metric called at timestamp
        - name: metric_value
          description: percentage of availability over the 24 hours preceeding metric_created_at
          tests:
              - not_null
        - name: result_type
        - name: status_type
          description: status of the query
        - name: message_type
        - name: status_code
          description: http status code of the request
        - name: is_success
          description: boolean, true if request was successful (200)
