{{ config(materialized='table') }}

WITH final as (

SELECT

--mart_arr_all columns
    mart_arr_all.arr_month,
    mart_arr_all.dim_billing_account_id,
    mart_arr_all.dim_crm_account_id,
    mart_arr_all.dim_subscription_id,
    mart_arr_all.dim_product_detail_id,
    mart_arr_all.fiscal_quarter_name_fy,
    mart_arr_all.fiscal_year,
    mart_arr_all.subscription_start_month,
    mart_arr_all.subscription_end_month,
    mart_arr_all.sold_to_country,
    mart_arr_all.billing_account_name,
    mart_arr_all.billing_account_number,
    mart_arr_all.ssp_channel,
    mart_arr_all.po_required,
    mart_arr_all.auto_pay,
    mart_arr_all.default_payment_method_type,
    mart_arr_all.crm_account_name,
    mart_arr_all.dim_parent_crm_account_id,
    mart_arr_all.parent_crm_account_name,
    mart_arr_all.parent_crm_account_sales_segment,
    mart_arr_all.parent_crm_account_industry,
    mart_arr_all.crm_account_employee_count_band,
    mart_arr_all.health_score_color,
    mart_arr_all.health_number,
    mart_arr_all.is_jihu_account,
    mart_arr_all.parent_crm_account_lam,
    mart_arr_all.parent_crm_account_lam_dev_count,
    mart_arr_all.parent_crm_account_business_unit,
    mart_arr_all.parent_crm_account_geo,
    mart_arr_all.parent_crm_account_region,
    mart_arr_all.parent_crm_account_area,
    mart_arr_all.parent_crm_account_role_type,
    mart_arr_all.parent_crm_account_territory,
    mart_arr_all.parent_crm_account_max_family_employee,
    mart_arr_all.parent_crm_account_upa_country,
    mart_arr_all.parent_crm_account_upa_state,
    mart_arr_all.parent_crm_account_upa_city,
    mart_arr_all.parent_crm_account_upa_street,
    mart_arr_all.parent_crm_account_upa_postal_code,
    mart_arr_all.crm_account_employee_count,
    mart_arr_all.dim_subscription_id_original,
    mart_arr_all.subscription_status,
    mart_arr_all.subscription_sales_type,
    mart_arr_all.subscription_name,
    mart_arr_all.subscription_name_slugify,
    mart_arr_all.oldest_subscription_in_cohort,
    mart_arr_all.subscription_lineage,
    mart_arr_all.subscription_cohort_month,
    mart_arr_all.subscription_cohort_quarter,
    mart_arr_all.billing_account_cohort_month,
    mart_arr_all.billing_account_cohort_quarter,
    mart_arr_all.crm_account_cohort_month,
    mart_arr_all.crm_account_cohort_quarter,
    mart_arr_all.parent_account_cohort_month,
    mart_arr_all.parent_account_cohort_quarter,
    mart_arr_all.auto_renew_native_hist,
    mart_arr_all.auto_renew_customerdot_hist,
    mart_arr_all.turn_on_cloud_licensing,
    mart_arr_all.turn_on_operational_metrics,
    mart_arr_all.contract_operational_metrics,
    mart_arr_all.contract_auto_renewal,
    mart_arr_all.turn_on_auto_renewal,
    mart_arr_all.contract_seat_reconciliation,
    mart_arr_all.turn_on_seat_reconciliation,
    mart_arr_all.invoice_owner_account,
    mart_arr_all.creator_account,
    mart_arr_all.was_purchased_through_reseller,
    mart_arr_all.product_tier_name,
    mart_arr_all.product_delivery_type,
    mart_arr_all.product_deployment_type,
    mart_arr_all.product_category,
    mart_arr_all.product_rate_plan_category,
    mart_arr_all.product_ranking,
    mart_arr_all.service_type,
    mart_arr_all.product_rate_plan_name,
    mart_arr_all.is_licensed_user,
    mart_arr_all.is_arpu,
    mart_arr_all.unit_of_measure,
    mart_arr_all.mrr,
    mart_arr_all.arr,
    mart_arr_all.quantity,
    mart_arr_all.months_since_billing_account_cohort_start,
    mart_arr_all.quarters_since_billing_account_cohort_start,
    mart_arr_all.months_since_crm_account_cohort_start,
    mart_arr_all.quarters_since_crm_account_cohort_start,
    mart_arr_all.months_since_parent_account_cohort_start,
    mart_arr_all.quarters_since_parent_account_cohort_start,
    mart_arr_all.months_since_subscription_cohort_start,
    mart_arr_all.quarters_since_subscription_cohort_start,
    mart_arr_all.arr_band_calc,
    mart_arr_all.child_account_base_arr,
    mart_arr_all.child_arr_rank,
    mart_arr_all.is_top_100_child_account_by_arr_month,

-- rpt_product_usage_health_score columns
    rpt_product_usage_health_score.snapshot_month,
    rpt_product_usage_health_score.customer_since_date,
    rpt_product_usage_health_score.account_age_months,
    rpt_product_usage_health_score.subscription_age_months,
    rpt_product_usage_health_score.combined_instance_creation_date,
    rpt_product_usage_health_score.instance_age_days,
    rpt_product_usage_health_score.instance_age_months,
    rpt_product_usage_health_score.subscription_start_date,
    rpt_product_usage_health_score.ultimate_subscription_flag,
    rpt_product_usage_health_score.is_oss_program,
    rpt_product_usage_health_score.instance_type,
    rpt_product_usage_health_score.included_in_health_measures_str,
    rpt_product_usage_health_score.uuid,
    rpt_product_usage_health_score.hostname,
    rpt_product_usage_health_score.dim_namespace_id,
    rpt_product_usage_health_score.dim_installation_id,
    rpt_product_usage_health_score.instance_identifier,
    rpt_product_usage_health_score.hostname_or_namespace_id,
    rpt_product_usage_health_score.ping_created_at,
    rpt_product_usage_health_score.cleaned_version,
    rpt_product_usage_health_score.license_utilization,
    rpt_product_usage_health_score.billable_user_count,
    rpt_product_usage_health_score.license_user_count,
    rpt_product_usage_health_score.license_user_count_source,
    rpt_product_usage_health_score.license_utilization_score,
    rpt_product_usage_health_score.license_utilization_color,
    rpt_product_usage_health_score.last_activity_28_days_user,
    rpt_product_usage_health_score.user_engagement,
    rpt_product_usage_health_score.user_engagement_score,
    rpt_product_usage_health_score.user_engagement_color,
    rpt_product_usage_health_score.action_monthly_active_users_project_repo_28_days_user_clean,
    rpt_product_usage_health_score.git_operation_utilization,
    rpt_product_usage_health_score.scm_score,
    rpt_product_usage_health_score.scm_color,
    rpt_product_usage_health_score.ci_pipelines_28_days_user,
    rpt_product_usage_health_score.ci_pipeline_utilization,
    rpt_product_usage_health_score.ci_builds_28_days_user,
    rpt_product_usage_health_score.ci_builds_all_time_user,
    rpt_product_usage_health_score.ci_builds_all_time_event,
    rpt_product_usage_health_score.ci_runners_all_time_event,
    rpt_product_usage_health_score.ci_builds_28_days_event,
    rpt_product_usage_health_score.ci_pipeline_utilization_score,
    rpt_product_usage_health_score.ci_pipeline_utilization_color,
    rpt_product_usage_health_score.ci_score,
    rpt_product_usage_health_score.ci_color,
    rpt_product_usage_health_score.deployments_28_days_user,
    rpt_product_usage_health_score.deployments_28_days_event,
    rpt_product_usage_health_score.successful_deployments_28_days_event,
    rpt_product_usage_health_score.failed_deployments_28_days_event,
    rpt_product_usage_health_score.completed_deployments_l28d,
    rpt_product_usage_health_score.projects_all_time_event,
    rpt_product_usage_health_score.environments_all_time_event,
    rpt_product_usage_health_score.deployments_utilization,
    rpt_product_usage_health_score.deployments_utilization_score,
    rpt_product_usage_health_score.deployments_utilization_color,
    rpt_product_usage_health_score.deployments_per_user_l28d,
    rpt_product_usage_health_score.deployments_per_user_l28d_score,
    rpt_product_usage_health_score.deployments_per_user_l28d_color,
    rpt_product_usage_health_score.successful_deployments_pct,
    rpt_product_usage_health_score.successful_deployments_pct_score,
    rpt_product_usage_health_score.successful_deployments_pct_color,
    rpt_product_usage_health_score.cd_measure_count,
    rpt_product_usage_health_score.cd_score,
    rpt_product_usage_health_score.cd_color,
    rpt_product_usage_health_score.user_unique_users_all_secure_scanners_28_days_user,
    rpt_product_usage_health_score.ci_internal_pipelines_28_days_event,
    rpt_product_usage_health_score.secret_detection_scans_28_days_event,
    rpt_product_usage_health_score.dependency_scanning_scans_28_days_event,
    rpt_product_usage_health_score.container_scanning_scans_28_days_event,
    rpt_product_usage_health_score.dast_scans_28_days_event,
    rpt_product_usage_health_score.sast_scans_28_days_event,
    rpt_product_usage_health_score.coverage_fuzzing_scans_28_days_event,
    rpt_product_usage_health_score.api_fuzzing_scans_28_days_event,
    rpt_product_usage_health_score.sum_of_all_scans_l28d,
    rpt_product_usage_health_score.secret_detection_scan_percentage,
    rpt_product_usage_health_score.dependency_scanning_scan_percentage,
    rpt_product_usage_health_score.container_scanning_scan_percentage,
    rpt_product_usage_health_score.dast_scan_percentage,
    rpt_product_usage_health_score.sast_scan_percentage,
    rpt_product_usage_health_score.coverage_fuzzing_scan_percentage,
    rpt_product_usage_health_score.api_fuzzing_scan_percentage,
    rpt_product_usage_health_score.secure_scanners_utilization,
    rpt_product_usage_health_score.secure_scanners_utilization_score,
    rpt_product_usage_health_score.secure_scanners_utilization_color,
    rpt_product_usage_health_score.average_scans_per_pipeline,
    rpt_product_usage_health_score.average_scans_per_pipeline_score,
    rpt_product_usage_health_score.average_scans_per_pipeline_color,
    rpt_product_usage_health_score.secret_detection_usage_flag,
    rpt_product_usage_health_score.dependency_scanning_usage_flag,
    rpt_product_usage_health_score.container_scanning_usage_flag,
    rpt_product_usage_health_score.dast_usage_flag,
    rpt_product_usage_health_score.sast_usage_flag,
    rpt_product_usage_health_score.coverage_fuzzing_usage_flag,
    rpt_product_usage_health_score.api_fuzzing_usage_flag,
    rpt_product_usage_health_score.number_of_scanner_types,
    rpt_product_usage_health_score.number_of_scanner_types_score,
    rpt_product_usage_health_score.number_of_scanner_types_color,
    rpt_product_usage_health_score.security_measure_count,
    rpt_product_usage_health_score.security_score,
    rpt_product_usage_health_score.security_color,
    rpt_product_usage_health_score.security_score_ultimate_only,
    rpt_product_usage_health_score.security_color_ultimate_only,
    rpt_product_usage_health_score.license_utilization_weight,
    rpt_product_usage_health_score.user_engagement_weight,
    rpt_product_usage_health_score.scm_weight,
    rpt_product_usage_health_score.ci_weight,
    rpt_product_usage_health_score.cd_weight,
    rpt_product_usage_health_score.security_weight,
    rpt_product_usage_health_score.remaining_weight,
    rpt_product_usage_health_score.adjusted_license_utilization_weight,
    rpt_product_usage_health_score.adjusted_user_engagement_weight,
    rpt_product_usage_health_score.adjusted_scm_weight,
    rpt_product_usage_health_score.adjusted_ci_weight,
    rpt_product_usage_health_score.adjusted_cd_weight,
    rpt_product_usage_health_score.adjusted_security_weight,
    rpt_product_usage_health_score.adjusted_license_utilization_score,
    rpt_product_usage_health_score.adjusted_user_engagement_score,
    rpt_product_usage_health_score.adjusted_scm_score,
    rpt_product_usage_health_score.adjusted_ci_score,
    rpt_product_usage_health_score.adjusted_cd_score,
    rpt_product_usage_health_score.adjusted_security_score,
    rpt_product_usage_health_score.overall_product_score,
    rpt_product_usage_health_score.overall_product_color,
    rpt_product_usage_health_score.scm_adopted,
    rpt_product_usage_health_score.ci_adopted,
    rpt_product_usage_health_score.cd_adopted,
    rpt_product_usage_health_score.security_adopted,
    rpt_product_usage_health_score.total_use_cases_adopted,
    rpt_product_usage_health_score.adopted_use_case_names_array,
    rpt_product_usage_health_score.adopted_use_case_names_string,
    rpt_product_usage_health_score.is_primary_instance_subscription,
    rpt_product_usage_health_score.ci_color_previous_month,
    rpt_product_usage_health_score.ci_color_previous_3_month,
    rpt_product_usage_health_score.ci_pipeline_utilization_previous_month,
    rpt_product_usage_health_score.ci_pipeline_utilization_previous_3_month,
    rpt_product_usage_health_score.scm_color_previous_month,
    rpt_product_usage_health_score.scm_color_previous_3_month,
    rpt_product_usage_health_score.git_operation_utilization_previous_month,
    rpt_product_usage_health_score.git_operation_utilization_previous_3_month,
    rpt_product_usage_health_score.cd_color_previous_month,
    rpt_product_usage_health_score.cd_color_previous_3_month,
    rpt_product_usage_health_score.security_color_previous_month,
    rpt_product_usage_health_score.security_color_previous_3_month,

--Ci Score Roll Up
    (rpt_product_usage_health_score.ci_pipeline_utilization) * (mart_arr_all.arr) AS ci_utilization_dollar,
    sum(rpt_product_usage_health_score.ci_utilization_dollar) OVER (PARTITION BY mart_arr_all.arr_month, mart_arr_all.dim_crm_account_id) as total_account_ci_utilization_dollar,
    div0(total_account_ci_utilization_dollar,child_account_base_arr) as weighted_ci_adoption_child_account,
    CASE WHEN weighted_ci_adoption_child_account > 0.33 THEN 88
         WHEN weighted_ci_adoption_child_account >= 0.1 AND weighted_ci_adoption_child_account <=0.33 THEN 63
         WHEN weighted_ci_adoption_child_account < 0.1 THEN 25
         ELSE NULL END AS ci_score_child_account,
    CASE WHEN weighted_ci_adoption_child_account > 0.33 THEN 'Green'
         WHEN weighted_ci_adoption_child_account >= 0.1 AND weighted_ci_adoption_child_account <=0.33 THEN 'Yellow'
         WHEN weighted_ci_adoption_child_account < 0.1 THEN 'Red'
         ELSE 'NO DATA AT ALL' END AS ci_color_child_account

FROM
  {{ ref('mart_arr_with_zero_dollar_charges') }} AS     mart_arr_all
  LEFT JOIN {{ ref('rpt_product_usage_health_score') }} AS  rpt_product_usage_health_score
    ON  rpt_product_usage_health_score.dim_subscription_id_original =    mart_arr_all.dim_subscription_id_original
    AND     rpt_product_usage_health_score.snapshot_month =     mart_arr_all.arr_month
    AND     rpt_product_usage_health_score.delivery_type =  mart_arr_all.product_delivery_type
)

SELECT 
  *
FROM final