version: 2

models:
  - name: oci_cost_report_source
    columns:
        - name: line_item_reference_no
          description: The primary key for oci line item cost data
          data_tests:
            - unique
            - not_null
