version: 2

models:
  - name: rpt_delta_arr_parent_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_month_8th_calendar_day") }}'

  - name: rpt_delta_arr_parent_product_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_product_month_8th_calendar_day") }}'

  - name: rpt_crm_opportunity_snapshot_8th_calendar_day
    description: Snapshot of mart_crm_opportunity_daily_snapshot taken on the 8th calendar day after month-end close.
    columns:
      - name: crm_opportunity_snapshot_id
        data_tests:
          - not_null
          - unique
    
  - name: rpt_crm_opportunity_renewal
    description: '{{ doc("rpt_crm_opportunity_renewal") }}'

  - name: rpt_crm_opportunity_open
    description: '{{ doc("rpt_crm_opportunity_open") }}'

  - name: rpt_gtm_crm_actuals
    description: A report table with the GTM actuals contained in the GTM Operating Performance Tableau dashboard.

  - name: rpt_gtm_pivoted_targets
    description: Pivoted targets for the GTM Operating Performance KPI's - putting each KPI's target into its own column, instead of the kpi_name format.

  - name: rpt_gtm_scaffold
    description: A scaffold table which contains all of the needed combinations of dimensions for joining (via a Tableau relationship) the GTM actuals and targets report tables.