version: 2
models:
  - name: level_up_course_actions_source
    description: Returns information when a user enrolls, changes status, earns a certificate, or has their access revoked in a course.
    columns:
      - name: course_action_id
        data_tests:
          - not_null
          - unique
      - name: company_id
      - name: course_sku
      - name: course_title
      - name: company_id
      - name: notifiable_id
      - name: course_action
        data_tests:
          - not_null
      - name: event_timestamp
        data_tests:
          - not_null
      - name: transaction_type
      - name: username
      - name: user_id
      - name: user_state
      - name: user_country
      - name: user_client
      - name: external_customer_id
      - name: ref1_user_type
      - name: ref2_user_job
      - name: ref4_user_company
      - name: ref6_user_role_type
      - name: ref7_user_continent
      - name: ref8_user_country
      - name: ref9_user_sub_dept
      - name: ref10_user_dept
      - name: sf_account_id
      - name: sf_contact_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_course_completions_source
    description: Returns information when a course is completed by a user
    columns:
      - name: course_completion_id
        data_tests:
          - not_null
          - unique
      - name: company_id
      - name: event
      - name: license
      - name: notifiable_id
      - name: course_action
      - name: event_timestamp
        data_tests:
          - not_null
      - name: title
      - name: transaction_type
      - name: updated_at
      - name: username
      - name: user_id
      - name: user_state
      - name: user_country
      - name: user_client
      - name: ref1_user_type
      - name: ref2_user_job
      - name: ref4_user_company
      - name: ref6_user_role_type
      - name: ref7_user_continent
      - name: ref8_user_country
      - name: ref9_user_sub_dept
      - name: ref10_user_dept
      - name: sf_account_id
      - name: sf_contact_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_course_purchases_source
    description: Returns information about course purchases
    columns:
      - name: course_purchase_id
        data_tests:
          - not_null
          - unique
      - name: transaction_id
      - name: gift_recipient_email
      - name: timestamp
      - name: company_id
      - name: coupon
      - name: coupon_code
      - name: purchasable_id
      - name: purchasable_type
      - name: charge_id
      - name: group_id
      - name: order_id
      - name: revenue_type
      - name: quantity
      - name: variation
      - name: shipping_method
      - name: transaction_type
      - name: course_sku
      - name: course_slug
      - name: course_title
      - name: course_start_date
      - name: is_success
      - name: failure_code
      - name: failure_message
      - name: username
      - name: user_id
      - name: stripe_customer_id
      - name: sf_contact_id
      - name: sf_account_id
      - name: referral_referrer
      - name: referral_referrer_type
      - name: referral_source
  - name: level_up_course_views_source
    description: Returns information about pages within courses that are viewed as a learner
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - event_timestamp
            - topic_title
    columns:
      - name: company_id
      - name: course_id
      - name: course_sku
      - name: course_title
      - name: lesson_id
      - name: lesson_slug
      - name: lesson_title
      - name: section_id
      - name: section_slug
      - name: section_title
      - name: event_timestamp
        data_tests:
          - not_null
      - name: topic_id
      - name: topic_title
      - name: username
      - name: user_id
      - name: user_state
      - name: user_country
      - name: user_type
      - name: ref1_user_type
      - name: ref2_user_job
      - name: ref4_user_company
      - name: ref6_user_role_type
      - name: ref7_user_continent
      - name: ref8_user_country
      - name: ref9_user_sub_dept
      - name: ref10_user_dept
      - name: sf_account_id
      - name: sf_contact_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_code_redemptions_source
    description: Returns information when either a redemption or a registration code is redeemed by a learner
    columns:
      - name: company_host
      - name: company_id
      - name: company_subdomain
      - name: event
      - name: redemption_code
        data_tests:
          - not_null
      - name: redemption_code_group_label
      - name: event_timestamp
      - name: username
      - name: user_id
        data_tests:
          - not_null
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_email_captures_source
    description: Returns information when an email is entered by a user on a course paywall or waitlist.
    columns:
      - name: notifiable_type
      - name: course_sku
      - name: course_id
        data_tests:
          - not_null
      - name: company_id
      - name: company_host
      - name: company_subdomain
      - name: course_title
      - name: anonymous_id
      - name: source
      - name: notifiable_id
      - name: event_timestamp
        data_tests:
          - not_null
      - name: username
      - name: event
      - name: email_capture_id
        data_tests:
          - not_null
          - unique
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_learning_path_actions_source
    description: Returns information when a learner enrolls, changes status, earns a certificate, or has their access revoked in a learning path.
    columns:
      - name: learning_path_action_id
        data_tests:
          - not_null
          - unique
      - name: source
      - name: event_timestamp
      - name: transaction_type
      - name: username
      - name: company_id
      - name: notifiable_id
      - name: learning_path_title
      - name: learning_path_sku
      - name: milestone_title
      - name: user_id
      - name: sf_contact_id
      - name: sf_account_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_logins_source
    description: Returns information about logins. It includes browser & IP Address information
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - event_timestamp
    columns:
      - name: browser_info
      - name: company_host
      - name: company_id
      - name: company_subdomain
      - name: event
      - name: event_timestamp
        data_tests:
          - not_null
      - name: user_agent
      - name: username
      - name: user_id
      - name: ref1_user_type
      - name: ref2_user_job
      - name: sf_account_id
      - name: sf_contact_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_visits_source
    description: Returns information about logged-in users visiting the platform
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - event_timestamp
    columns:
      - name: company_host
      - name: company_id
      - name: company_subdomain
      - name: event
      - name: event_timestamp
        data_tests:
          - not_null
      - name: username
      - name: user_id
      - name: user_client_id
      - name: user_department_id
      - name: ref1_user_type
      - name: ref2_user_job
      - name: sf_account_id
      - name: sf_contact_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_assessment_attempt_answers_source
    description: Returns the answers associated with an assessment
    columns:
      - name: assessment_attempt_id
        data_tests:
          - not_null
      - name: answer
      - name: is_correct
      - name: answer_id
        data_tests:
          - not_null
          - unique
      - name: question
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_assessment_attempts_source
    description: Returns information when an assessment is taken
    columns:
      - name: assessment_id
      - name: assessment_title
      - name: assessment_type
      - name: course_title
      - name: course_id
      - name: created_at
      - name: grade
      - name: assessment_attempt_id
        data_tests:
          - not_null
          - unique
      - name: has_passed
      - name: status
      - name: time_elapsed_in_seconds
      - name: updated_at
      - name: client_id
      - name: username
      - name: user_id
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_clients_source
    description: Returns all Clients within the school
    columns:
      - name: created_at
      - name: is_disabled
      - name: client_id
        data_tests:
          - not_null
          - unique
      - name: name
      - name: sku
      - name: slug
      - name: tags
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_content_source
    description: Returns all Content within the school
    columns:
      - name: asset
      - name: asset_alt_text
      - name: authors_and_instructors
      - name: content_type_label
      - name: course_end_date
      - name: course_start_date
      - name: created_at
      - name: custom_fields
      - name: description
      - name: enrollment_count
      - name: enrollment_end_date
      - name: enrollment_start_date
      - name: is_free_with_registration
      - name: has_children
      - name: content_id
        data_tests:
          - not_null
          - unique
      - name: kind
      - name: language
      - name: meta_description
      - name: meta_title
      - name: price_in_cents
      - name: seats_limit
      - name: sku
      - name: slug
      - name: source
      - name: status
      - name: suggested_retail_price_in_cents
      - name: tags
      - name: title
      - name: updated_at
      - name: url
      - name: waitlist_count
      - name: is_waitlisting_enabled
      - name: is_waitlisting_triggered
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_coupons_source
    description: Returns all global coupons that have been created
    columns:
      - name: is_active
      - name: allow_multiple_in_cart
      - name: amount_off_in_cents
      - name: applies_to_user
      - name: coupon_code
      - name: coupon_id
        data_tests:
          - not_null
          - unique
      - name: max_redemptions
      - name: percent_off
      - name: redeem_by
      - name: times_redeemed
      - name: uploaded_at
        data_tests:
          - not_null
  - name: level_up_meetings_source
    description: Returns all meetings within the school
    columns:
      - name: attendee_info
      - name: course_id
      - name: course_title
      - name: meeting_end_date
      - name: meeting_id
        data_tests:
          - not_null
          - unique
      - name: instructors
      - name: location
      - name: meeting_start_date
      - name: meeting_title
      - name: uploaded_at
        data_tests:
          - not_null
