version: 2

models:

  - name: fct_behavior_link_click
    description: A derived fact from fct_behavior_unstructured_event containing only link_click event types.
    columns: 
      - name: fct_behavior_unstructured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_redis_hll_counters
    description: Derived fact table for structured events related to redis hll metrics.
    columns:
      - name: behavior_structured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_service_ping_context
    description: Derived fact table that parses out the Redis event from the Service Ping context which can optionally be sent with an event.
    columns:
      - name: behavior_structured_event_pk
        tests:
        - unique:
            config:
              where: "behavior_at >= DATEADD('day',-3,CURRENT_DATE())"
        - not_null