WITH source AS (

    SELECT 
      user_id,
      remember_created_at,
      sign_in_count,
      current_sign_in_at,
      last_sign_in_at,
      created_at,
      updated_at,
      is_admin,
      projects_limit,
      failed_attempts,
      locked_at,
      user_locked,
      has_create_group_permissions,
      has_create_team_permissions,
      state,
      color_scheme_id,
      password_expires_at,
      created_by_id,
      last_credential_check_at,
      has_avatar,
      confirmed_at,
      confirmation_sent_at,
      has_hide_no_ssh_key_enabled,
      admin_email_unsubscribed_at,
      notification_email,
      notification_email_domain,
      has_hide_no_password_enabled,
      is_password_automatically_set,
      location,
      email,
      email_domain,
      public_email,
      public_email_domain,
      commit_email,
      commit_email_domain,
      is_email_opted_in,
      email_opted_in_source_id,
      email_opted_in_at,
      dashboard,
      project_view,
      consumed_timestep,
      layout,
      has_hide_project_limit_enabled,
      otp_grace_period_started_at,
      is_external_user,
      organization,
      auditor,
      does_require_two_factor_authentication_from_group,
      two_factor_grace_period,
      last_activity_on,
      is_notified_of_own_activity,
      preferred_language,
      theme_id,
      accepted_term_id,
      is_private_profile,
      roadmap_layout,
      include_private_contributions,
      group_view,
      managing_group_id,
      role_id,
      role,
      user_name,
      first_name,
      last_name,
      users_name,
      user_type_id,
      user_type
    FROM {{ ref('gitlab_dotcom_users_source') }}

)

SELECT *
FROM source
