SELECT
  mart_sales_funnel_target_daily.primary_key,
  mart_sales_funnel_target_daily.target_date,
  mart_sales_funnel_target_daily.report_target_date,
  mart_sales_funnel_target_daily.first_day_of_week,
  mart_sales_funnel_target_daily.target_month,
  mart_sales_funnel_target_daily.fiscal_quarter_name,
  mart_sales_funnel_target_daily.fiscal_quarter_name_fy,
  mart_sales_funnel_target_daily.fiscal_year,
  mart_sales_funnel_target_daily.kpi_name,
  mart_sales_funnel_target_daily.crm_user_sales_segment,
  mart_sales_funnel_target_daily.crm_user_sales_segment_grouped,
  mart_sales_funnel_target_daily.crm_user_business_unit,
  mart_sales_funnel_target_daily.crm_user_geo,
  mart_sales_funnel_target_daily.crm_user_region,
  mart_sales_funnel_target_daily.crm_user_area,
  mart_sales_funnel_target_daily.crm_user_sales_segment_region_grouped,
  mart_sales_funnel_target_daily.crm_user_role_name,
  mart_sales_funnel_target_daily.crm_user_role_level_1,
  mart_sales_funnel_target_daily.crm_user_role_level_2,
  mart_sales_funnel_target_daily.crm_user_role_level_3,
  mart_sales_funnel_target_daily.crm_user_role_level_4,
  mart_sales_funnel_target_daily.crm_user_role_level_5,
  mart_sales_funnel_target_daily.order_type_name,
  mart_sales_funnel_target_daily.order_type_grouped,
  mart_sales_funnel_target_daily.sales_qualified_source_name,
  mart_sales_funnel_target_daily.sales_qualified_source_grouped,
  mart_sales_funnel_target_daily.monthly_allocated_target,
  mart_sales_funnel_target_daily.daily_allocated_target,
  mart_sales_funnel_target_daily.wtd_allocated_target,
  mart_sales_funnel_target_daily.mtd_allocated_target,
  mart_sales_funnel_target_daily.qtd_allocated_target,
  mart_sales_funnel_target_daily.ytd_allocated_target,
  dim_date.fiscal_year                     AS date_range_year,
  dim_date.fiscal_quarter_name_fy          AS date_range_quarter,
  DATE_TRUNC(month, dim_date.date_actual)  AS date_range_month,
  dim_date.date_id                         AS date_range_id,
  dim_date.fiscal_month_name_fy,
  dim_date.first_day_of_fiscal_quarter
FROM {{ ref('mart_sales_funnel_target_daily') }}
LEFT JOIN {{ ref('dim_date') }}
  ON mart_sales_funnel_target_daily.target_date = dim_date.date_actual
